### ISSUE TITLE
InvalidStateError when setting timeout options on IE9>

### ISSUE THREAD

**Issue by fdhub** [wylst/http.js#11]
Hi, i'm using this nice library since a couple of months and so far it's working well on chrome, firefox and ie, majorly. I'm having some issues with timeout options on IE>9 and i just want to know if there is any known issue with ie when setting an option after XMLHttpRequest instantiation;

For instance; when i pass these options; 
```javascript
	var options = {
        url: someValidUrl,
        data: { //valid json data },
        timeout: 5000,
        props: ['timeout', 'ontimeout'],
        onload: function () {
            //stuff
        },
        onerror: function () {
            //stuff
        },
        ontimeout: function () {
			//stuff
        }
    };
	http.get(options);
```
IE throws an error on commented line (on the request method)
	var req = new XMLHttpRequest();

	// Copy properties
	for (var i = 0; i < options.props.length; i++) {
		var key = options.props[i];
		req[key] = options[key];	// => throws a InvalidStateError Here
	}

	req.open(options.method, options.url, options.async);
	
I think that IE doesn't allow etting requests properties/headers when the XMLHttpRequest object is already instantiated.

Can you provide some advice here? Thanks

**Comment by denikeweb** [comment]
I worked with something like this last time more than 2 years ago, so I forgot specific moments. If you have problems only with IE in versions 10 or higher, I have no ideas. I use jQuery for AJAX. I remember that IE needs some specific code (but it is including old versions). If it is your real code, the problem in line [data: { //valid json data },] — there are commented your second figure bracket there (it is in one line after "//").

**Comment by fdhub** [comment]
Thanks @denikeweb that's just an example (about the json). It's working fine without the timeout options, so, i will remove and i'll handle this like a workaround.
Thanks.
